[kubernetes]
symbol = "☸  "
style = "bold italic yellow"
disabled = false

[terraform]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[directory]
#style = "fg:#E5E9F0 bg:#81A1C1"
#format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false
fish_style_pwd_dir_length = 5

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = " "
#style = "bg:#3B4252"
#format = '[[ $symbol $branch ](fg:#81A1C1 bg:#3B4252)]($style)'

[git_status]
style = "bg:#3B4252"
format = '[[($all_status$ahead_behind )](fg:#81A1C1)]($style)'

[nodejs]
disabled = true
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1)]($style)'

[rust]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[golang]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[php]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

