[kubernetes]
symbol = "☸  "
style = "bold italic yellow"
disabled = false

[kubernetes.context_aliases]
"eu-staging-staging-eu-nov20-EksUserGroupRbac" = "EKSv2.1 eu-west-staging"
"eu-dev-dev-eu-nov20-EksUserGroupRbac" = "EKSv2.1 eu-west-dev"
"eu-prod-production-eu-nov20-EksUserGroupRbac" = "EKSv2.1 eu-west-prod"
"eu-dev-dev-eu-jul21-EksUserGroupRbac" = "EKSv2.2 eu-west-dev"
"eu-staging-staging-eu-jul21-EksUserGroupRbac" = "EKSv2.2 eu-west-staging"
"eu-prod-production-eu-jul21-EksUserGroupRbac" = "EKSv2.2 eu-west-prod"

[terraform]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[directory]
truncation_length = 1
truncate_to_repo = false
fish_style_pwd_dir_length = 5

