[kubernetes]
symbol = "☸  "
disabled = false

[kubernetes.context_aliases]
"arn:aws:eks:ap-south-1:031330673814:cluster/dev-ap-south-1-eks" = "ap-south-dev"
"arn:aws:eks:ap-south-1:796835670434:cluster/staging-ap-south-1-eks" = "ap-south-staging"
"arn:aws:eks:ap-south-1:232889591658:cluster/prod-ap-south-1-eks" = "ap-south-prod"
"arn:aws:eks:eu-west-1:328632723344:cluster/dev-eu-west-1-eks" = "eu-west-dev"
"arn:aws:eks:eu-west-1:444377790215:cluster/staging-eu-west-1-eks" = "eu-west-staging"
"arn:aws:eks:eu-west-1:593794845141:cluster/prod-eu-west-1-eks" = "eu-west-prod"

[terraform]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[directory]
truncation_length = 1
truncate_to_repo = false
fish_style_pwd_dir_length = 5

